# Generated by Django 4.0.5 on 2022-06-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0004_remove_creator_course_remove_creator_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='images'),
        ),
    ]
