# Generated by Django 4.0.5 on 2022-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0006_alter_course_description_alter_enrolled_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
